
const env={
    APPWRITE_PROJECTID:String(import.meta.env.VITE_APPWRITE_PROJECTID),
    APPWRITE_ENDPOINT:String(import.meta.env.VITE_APPWRITE_ENDPOINT),
    APPWRITE_DB:String(import.meta.env.VITE_APPWRITE_DB),
    APPWRITE_PRODUCT_TABLE:String(import.meta.env.VITE_APPWRITE_PRODUCT_TABLE),
    APPWRITE_STORE_TABLE:String(import.meta.env.VITE_APPWRITE_STORE_TABLE),
    APPWRITE_SELLER_TABLE:String(import.meta.env.VITE_APPWRITE_SELLER_TABLE),
    APPWRITE_STORAGEID:String(import.meta.env.VITE_APPWRITE_STORAGEID),
    APPWRITE_REVIEWID:String(import.meta.env.VITE_APPWRITE_REVIEWID),
    APPWRITE_ADDRESSID:String(import.meta.env.VITE_APPWRITE_ADDRESSID),
    APPWRITE_PRODUCTQUERIEID:String(import.meta.env.VITE_APPWRITE_PRODUCTQUERIEID)

}

export default env;